
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "CATEGORIA DIVISOR GENERO ID ID_LING LINHA_BDic : EE :  Categoria LINHA_B Linguas Genero LINHA_B DIVISOR LINHA_B E E :  Categoria LINHA_B Linguas LINHA_B Genero LINHA_B DIVISOR Categoria : CATEGORIA ':' ItemsItems : '[' Item ']'Item :  IDItem :  ID ',' Item Genero : GENERO ':'  ID Linguas : ID_LING ':'  ID  LINHA_B Linguas Linguas : ID_LING ':'  ID  LINHA_B "
    
_lr_action_items = {'CATEGORIA':([0,29,],[4,4,]),'$end':([1,2,28,31,],[0,-1,-3,-2,]),'LINHA_B':([3,7,9,12,17,20,21,24,25,26,30,],[5,11,-4,18,23,26,-5,29,-8,-10,-9,]),':':([4,8,13,],[6,14,19,]),'ID_LING':([5,26,],[8,8,]),'[':([6,],[10,]),'GENERO':([7,11,26,30,],[13,13,-10,-9,]),'ID':([10,14,19,22,],[16,20,25,16,]),']':([15,16,27,],[21,-6,-7,]),',':([16,],[22,]),'DIVISOR':([18,23,],[24,28,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Dic':([0,],[1,]),'E':([0,29,],[2,31,]),'Categoria':([0,29,],[3,3,]),'Linguas':([5,26,],[7,30,]),'Items':([6,],[9,]),'Genero':([7,11,],[12,17,]),'Item':([10,22,],[15,27,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Dic","S'",1,None,None,None),
  ('Dic -> E','Dic',1,'p_1','yacc.py',15),
  ('E -> Categoria LINHA_B Linguas Genero LINHA_B DIVISOR LINHA_B E','E',8,'p_2','yacc.py',20),
  ('E -> Categoria LINHA_B Linguas LINHA_B Genero LINHA_B DIVISOR','E',7,'p_2_1','yacc.py',26),
  ('Categoria -> CATEGORIA : Items','Categoria',3,'p_3','yacc.py',31),
  ('Items -> [ Item ]','Items',3,'p_4','yacc.py',36),
  ('Item -> ID','Item',1,'p_4_1','yacc.py',41),
  ('Item -> ID , Item','Item',3,'p_4_2','yacc.py',47),
  ('Genero -> GENERO : ID','Genero',3,'p_5','yacc.py',52),
  ('Linguas -> ID_LING : ID LINHA_B Linguas','Linguas',5,'p_6','yacc.py',57),
  ('Linguas -> ID_LING : ID LINHA_B','Linguas',4,'p_6_1','yacc.py',62),
]
