
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "CATEGORIA DIVISOR GENERO ID ID_LING LINHA_B PA PFDic : EE :  Categoria LINHA_B Linguas LINHA_B Genero LINHA_B DIVISOR E E :  Categoria LINHA_B Linguas LINHA_B Genero LINHA_B DIVISOR Categoria : CATEGORIA ':' ItemsItems : PA Item PFItem :  ID Item :  ID ',' Item Genero : GENERO ':' PA ID PF Linguas : ID_LING ':'  ID  LINHA_B Linguas Linguas : ID_LING ':'  ID  LINHA_B "
    
_lr_action_items = {'CATEGORIA':([0,24,],[4,4,]),'$end':([1,2,24,27,],[0,-1,-3,-2,]),'LINHA_B':([3,7,9,15,17,18,22,26,29,],[5,11,-4,20,22,-5,-10,-9,-8,]),':':([4,8,16,],[6,12,21,]),'ID_LING':([5,22,],[8,8,]),'PA':([6,21,],[10,25,]),'ID':([10,12,19,25,],[14,17,14,28,]),'GENERO':([11,],[16,]),'PF':([13,14,23,28,],[18,-6,-7,29,]),',':([14,],[19,]),'DIVISOR':([20,],[24,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Dic':([0,],[1,]),'E':([0,24,],[2,27,]),'Categoria':([0,24,],[3,3,]),'Linguas':([5,22,],[7,26,]),'Items':([6,],[9,]),'Item':([10,19,],[13,23,]),'Genero':([11,],[15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Dic","S'",1,None,None,None),
  ('Dic -> E','Dic',1,'p_1','yacc.py',15),
  ('E -> Categoria LINHA_B Linguas LINHA_B Genero LINHA_B DIVISOR E','E',8,'p_2','yacc.py',20),
  ('E -> Categoria LINHA_B Linguas LINHA_B Genero LINHA_B DIVISOR','E',7,'p_2_1','yacc.py',25),
  ('Categoria -> CATEGORIA : Items','Categoria',3,'p_3','yacc.py',30),
  ('Items -> PA Item PF','Items',3,'p_4','yacc.py',35),
  ('Item -> ID','Item',1,'p_4_1','yacc.py',40),
  ('Item -> ID , Item','Item',3,'p_4_2','yacc.py',44),
  ('Genero -> GENERO : PA ID PF','Genero',5,'p_5','yacc.py',49),
  ('Linguas -> ID_LING : ID LINHA_B Linguas','Linguas',5,'p_6','yacc.py',54),
  ('Linguas -> ID_LING : ID LINHA_B','Linguas',4,'p_6_1','yacc.py',59),
]
